# -*- coding: utf-8 -*-
"""Untitled1220.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oM76qK6Vx9MS8upB3z0PVR-aCeQ_LtDa
"""

import pandas as pd



navi=pd.read_csv('PROJECT INFO.csv')
print(navi)

navi.head()

navi.tail()

navi.head(6)

it=pd.read_csv('pandas.csv')
print(it)

it.head()

it.tail()

it.columns

it[' Correct']

it[' Wrong']

it[' Correct'].unique()

